import {describe,it,expect} from 'vitest';
import {WALK_SPEED,SPRINT_SPEED} from '../src/player/PlayerTuning';
import {Vector3} from '@babylonjs/core/Maths/math.vector';
import {CollisionWorld} from '../src/physics/CollisionWorld';
import {PlayerMotor} from '../src/player/PlayerMotor';
import {EventBus} from '../src/core/EventBus';
import {EMPTY_INPUT,type InputFrame} from '../src/input/GameInput';
import {RicochetFan} from '../src/combat/RicochetFan';
import {DamageFeedback} from '../src/ui/DamageFeedback';
import {enemyImpact} from '../src/enemies/EnemyImpact';
import type {DamageContext} from '../src/core/contracts';
const frame=1/60;
function fixture(){const world=new CollisionWorld();world.surfaces.push({id:'floor',x:0,z:0,width:100,depth:100,height:0});return{world,player:new PlayerMotor(world,new EventBus(),{x:0,y:0,z:0})};}
function tick(p:PlayerMotor,n:number,input:Partial<InputFrame>={}){for(let i=0;i<n;i++)p.fixedUpdate(frame,{...EMPTY_INPUT,...input},0);}
const damage=(source='dual_pistols',force=2):DamageContext=>({attackerId:2,victimId:1,sourceId:source,attackId:'test',baseDamage:20,finalDamage:20,crit:false,procCoefficient:1,procChainDepth:0,damageTags:['bullet'],hitPosition:{x:0,y:1,z:0},hitNormal:{x:1,y:0,z:0},forceDirection:{x:0,y:0,z:1},forceMagnitude:force});
describe('responsive movement and damage',()=>{
 it('sprints after rolling, carries speed through a jump, and stops sprinting on fire or released movement',()=>{const{player}=fixture();tick(player,1,{z:1,dodge:true});tick(player,100,{z:1});expect(player.sprinting).toBe(true);expect(player.velocity.z).toBeCloseTo(SPRINT_SPEED,2);tick(player,1,{z:1,jump:true});tick(player,15,{z:1});expect(player.grounded).toBe(false);expect(player.velocity.z).toBeCloseTo(SPRINT_SPEED,2);tick(player,1,{z:1,fire:true});expect(player.sprinting).toBe(false);tick(player,50,{z:1});expect(player.velocity.z).toBeCloseTo(WALK_SPEED,2);tick(player,1,{z:1,dodge:true});tick(player,60,{z:1});tick(player,1);expect(player.sprinting).toBe(false);});
 it('blocks walking and dodging into a heavy enemy without moving its body',()=>{for(const dodge of [false,true]){const{world,player}=fixture(),body={x:0,y:0,z:3};world.playerBodies.set(9,{id:9,position:body,radius:1,height:2,active:()=>true});let bumped=false;tick(player,1,{z:1,dodge});for(let i=0;i<120;i++){tick(player,1,{z:1});bumped ||= player.bumpRemaining>0;}expect(bumped).toBe(true);expect(player.position.z).toBeLessThanOrEqual(1.656);expect(body).toEqual({x:0,y:0,z:3});expect(Math.abs(player.velocity.z)).toBeLessThan(.01);tick(player,90,{x:1,z:1});expect(player.position.x).toBeGreaterThan(3);}});
 it('does not block jumping above a short enemy or walking through its dead body',()=>{const{world,player}=fixture();let alive=true;world.playerBodies.set(9,{id:9,position:{x:0,y:0,z:1.5},radius:.5,height:.5,active:()=>alive});player.position.y=1;player.grounded=false;player.velocity.y=4;// Tempo derivado da caminhada: o teste prova que o corpo NÃO bloqueia, não a velocidade base.
  const steps=Math.ceil(2.6/WALK_SPEED*60)+18;tick(player,steps,{z:1});expect(player.position.z).toBeGreaterThan(2);alive=false;player.resetAt({x:0,y:0,z:0});tick(player,steps,{z:1});expect(player.position.z).toBeGreaterThan(2);});
 it('sweeps simultaneous rise and horizontal travel against an overhang corner',()=>{const{world,player}=fixture();world.boxes.push({id:'overhang',min:{x:-4,y:2,z:1},max:{x:4,y:4,z:1.03}});player.grounded=false;player.position.y=.1;player.velocity.y=12;player.velocity.z=12;for(let i=0;i<10;i++){tick(player,1,{z:1});expect(player.position.z+.32<=1.002||player.position.y+1.8<=2.002).toBe(true);}});
 it('wall jumps away from a thin wall and never crosses it while holding toward it',()=>{const{world,player}=fixture();world.boxes.push({id:'wall',min:{x:-4,y:0,z:1},max:{x:4,y:10,z:1.025}});tick(player,1,{z:1,jump:true});tick(player,14,{z:1});tick(player,1,{z:1,jump:true});expect(player.wallJumps).toBe(1);for(let i=0;i<90;i++){tick(player,1,{z:1,jump:i===10});expect(player.position.z).toBeLessThanOrEqual(.681);}expect(player.wallJumps).toBe(1);});
 it('keeps lost HP visible and delays regeneration after an actual hit',()=>{const{player}=fixture();player.applyDamage(damage());expect(player.hp).toBe(110);tick(player,60);expect(player.hp).toBe(110);tick(player,90);expect(player.hp).toBeGreaterThan(110);const feedback=new DamageFeedback();feedback.hit(20,1,{x:0,z:1},0);feedback.update(.4,110/130);expect(feedback.trail).toBe(1);expect(feedback.flash).toBeGreaterThan(0);feedback.update(.8,110/130);expect(feedback.trail).toBeLessThan(1);expect(feedback.amount).toBe(20);});
 it('never stunlocks with automatic pistol hits and gives strong impacts a refractory period',()=>{for(let i=0;i<30;i++){const hit=enemyImpact(damage(), 'normal','eggplant',0);expect(hit.stagger).toBe(false);expect(hit.force).toBeLessThan(.5);}expect(enemyImpact(damage('skill',8),'normal','eggplant',0).stagger).toBe(true);expect(enemyImpact(damage('skill',8),'normal','eggplant',.5).stagger).toBe(false);expect(enemyImpact(damage('skill',8),'giant','eggplant',0).force).toBeLessThan(2);});
});
describe('ricochet fan ballistics',()=>{
 it('opens on both sides, bends in flight without targets, and expires within its bound',()=>{const fan=new RicochetFan(()=>undefined,()=>{},()=>{});for(let i=0;i<10;i++)fan.launch(Vector3.Zero(),Vector3.Forward(),i);const initial=fan.bullets[0]!.direction.clone();for(let i=0;i<24;i++)fan.update(frame);expect(fan.bullets[0]!.position.x).toBeLessThan(-5);expect(fan.bullets[9]!.position.x).toBeGreaterThan(5);expect(Vector3.Distance(initial,fan.bullets[0]!.direction)).toBeGreaterThan(.1);for(let i=0;i<100;i++)fan.update(frame);expect(fan.bullets).toHaveLength(0);});
 it('reflects on a thin wall and cannot cross it even with a long update',()=>{let hits=0;const fan=new RicochetFan(ray=>{const d=(2-ray.origin.z)/ray.direction.z;if(ray.direction.z>0&&d>=0&&d<=ray.length)return{point:ray.origin.add(ray.direction.scale(d)),normal:new Vector3(0,0,-1),distance:d};},()=>hits++,()=>{});fan.launch(Vector3.Zero(),Vector3.Forward(),4);fan.update(.2);expect(hits).toBe(1);expect(fan.bullets[0]!.position.z).toBeLessThan(2);expect(fan.bullets[0]!.direction.z).toBeLessThan(0);});
 it('hits an enemy once per bullet and limits the number of ricochets',()=>{let hits=0;const fan=new RicochetFan((ray,ignore)=>ignore.has(7)?undefined:{point:ray.origin.add(ray.direction.scale(.1)),normal:ray.direction.negate(),distance:.1,targetId:7},()=>hits++,()=>{});fan.launch(Vector3.Zero(),Vector3.Forward(),4);for(let i=0;i<30;i++)fan.update(frame);expect(hits).toBe(1);let contacts=0;const trapped=new RicochetFan(ray=>({point:ray.origin.add(ray.direction.scale(.05)),normal:ray.direction.negate(),distance:.05}),()=>contacts++,()=>{});trapped.launch(Vector3.Zero(),Vector3.Forward(),4);trapped.update(frame);expect(contacts).toBe(3);expect(trapped.bullets).toHaveLength(0);});
});
