import {describe,it,expect} from 'vitest';
import {NullEngine} from '@babylonjs/core/Engines/nullEngine';
import {Scene} from '@babylonjs/core/scene';
import {AssetContainer} from '@babylonjs/core/assetContainer';
import {CreateBox} from '@babylonjs/core/Meshes/Builders/boxBuilder';
import {DirectionalLight} from '@babylonjs/core/Lights/directionalLight';
import {ShadowGenerator} from '@babylonjs/core/Lights/Shadows/shadowGenerator';
import {Vector3} from '@babylonjs/core/Maths/math.vector';
import {EventBus} from '../src/core/EventBus';
import type {GameEvents} from '../src/core/contracts';
import {RunRNG} from '../src/core/RunRNG';
import {RunProgression} from '../src/run/RunProgression';
import {EnemySwarm} from '../src/game/EnemySwarm';
import {CollisionWorld} from '../src/physics/CollisionWorld';
import {PlayerMotor} from '../src/player/PlayerMotor';
import {chooseSpawnAround} from '../src/ai/SpawnPlanner';
import type {TrainingTarget} from '../src/world/TrainingYard';
describe('probe',()=>{it('spawn no pos',async()=>{
  const engine=new NullEngine(),scene=new Scene(engine),events=new EventBus<GameEvents>(),collision=new CollisionWorld();
  collision.surfaces.push({id:'field',x:0,z:0,width:600,depth:600,height:0});
  const player=new PlayerMotor(collision,events,{x:0,y:0,z:0}),run=new RunProgression(events),world={targets:[] as TrainingTarget[],collision};
  const light=new DirectionalLight('sun',new Vector3(0,-1,0),scene),shadows=new ShadowGenerator(128,light);
  const swarm=new EnemySwarm(scene,world,events,shadows,player,run,new RunRNG('recycling-test'),'expedition');
  await swarm.load(async model=>{const c=new AssetContainer(scene),mesh=CreateBox(model,{size:1},scene);c.meshes.push(mesh);c.populateRootNodes();c.removeAllFromScene();return c;});
  swarm.initialize();swarm.director.stopped=true;
  const rng=new RunRNG('recycling-test');
  const p=chooseSpawnAround(player.position,rng.stream('enemySpawn'),collision,()=>true,()=>false);
  process.stdout.write(`chooseSpawnAround(always reachable)=${JSON.stringify(p)}\n`);
  process.stdout.write(`groundAt(20,10,6)=${collision.groundAt(20,10,6)}\n`);
  process.stdout.write(`ready=${swarm.ready} cap=${swarm.populationCap} count=${swarm.count}\n`);
  process.stdout.write(`spawn()=${swarm.spawn('eggplant')}\n`);
  expect(1).toBe(1);
  swarm.dispose();scene.dispose();engine.dispose();
},60000);});
