import {Vector3,Matrix} from '@babylonjs/core/Maths/math.vector';
import type {Camera} from '@babylonjs/core/Cameras/camera';
import type {EnemySwarm} from '../game/EnemySwarm';
import {ITEMS,type RunProgression} from '../run/RunProgression';
import type {RunInteractables} from '../run/RunInteractables';
import {ENEMY_AFFIXES} from '../enemies/EnemyAffixes';
import {ENEMIES} from '../run/MonsterDirector';
import {perkIcon} from './PerkIcons';

export class RunHUD {
 private readonly element=document.createElement('div');private readonly controls=new AbortController();private inventoryKey='';private lastUpdate=-1;
 constructor(){
  this.element.id='run-hud';this.element.innerHTML='<div class="run-inventory"></div><div class="run-clock"></div><div class="run-mission"></div><aside class="district-contract"></aside><div class="run-boss" hidden><span>PRAGA ALFA</span><div><i></i></div><small></small></div><div class="run-xp"><span></span><div><i></i></div></div><div class="run-hostiles"></div><div class="run-interact" hidden></div><div class="run-toast"></div><div class="damage-labels"></div><div class="run-bearing"></div><div class="world-supplies"></div><div class="enemy-health-bars"></div><aside class="run-stats" hidden></aside><small class="stats-hint">TAB · ATRIBUTOS</small>';document.body.append(this.element);
  window.addEventListener('keydown',event=>{if(event.code==='Tab'&&!this.element.hidden){event.preventDefault();const panel=this.element.querySelector('.run-stats') as HTMLElement;panel.hidden=!panel.hidden;}},{signal:this.controls.signal});

 }
 setVisible(visible:boolean):void {this.element.hidden=!visible;document.getElementById('player-hud')?.classList.toggle('run-active',visible);}
 private html(selector:string,text:string):void {this.element.querySelector(selector)!.innerHTML=text;}
 update(run:RunProgression,swarm:EnemySwarm,interact:RunInteractables,camera:Camera):void {
  if(run.time>=this.lastUpdate&&run.time-this.lastUpdate<.1)return;this.lastUpdate=run.time;
  const key=[...run.inventory].join();if(key!==this.inventoryKey){this.inventoryKey=key;this.html('.run-inventory',[...run.inventory].slice(0,12).map(([id,count])=>{const item=ITEMS.find(x=>x.id===id)!;return `<div title="${item.name}: ${item.description}"><i class="item-icon" style='${perkIcon(item.icon)}'></i><b>×${count}</b></div>`;}).join('')+(run.inventory.size>12?'<small class=inventory-more>+'+(run.inventory.size-12)+' ITENS · TAB</small>':''));}
  const f=camera.getForwardRay().direction,heading=(Math.atan2(f.x,f.z)*180/Math.PI+360)%360,seconds=Math.floor(run.time);
  this.html('.run-bearing',`${['N','NE','L','SE','S','SO','O','NO'][Math.round(heading/45)%8]} · ${Math.round(heading)}°`);
  this.html('.run-clock',`<b>◷ ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}</b><span>ESTÁGIO ${run.stage} · ${['NORMAL','CRESCENTE','DIFÍCIL','CAÓTICA','PRAGA ALFA','FENDA'][swarm.director.state]}</span><strong>◈ ${run.credits} CRÉDITOS</strong>`);
  this.html('.run-mission',swarm.director.hordeMode?(swarm.director.intermission>0?'PRÓXIMA HORDA EM '+Math.ceil(swarm.director.intermission)+' s':swarm.director.wave%5===0?'ELIMINE O CHEFE E SUA HORDA':'SOBREVIVA À HORDA '+swarm.director.wave):swarm.bossDeadTime>=5?'ENTRE NA FENDA · CELEIRO':swarm.bossDeadTime>=0?'PRAGA ALFA DERROTADA':swarm.boss?'ELIMINE A PRAGA ALFA':['LOCALIZE A PRAGA ALFA','CONTENHA A INFESTAÇÃO','SOBREVIVA AO SURTO','RESISTA À COLHEITA FINAL','A PRAGA ALFA SE APROXIMA'][swarm.director.state]??'');
  const contract=interact.districtContract,contractDirection=contract?['↑','↗','→','↘','↓','↙','←','↖'][Math.round(((Math.atan2(contract.target.x-camera.position.x,contract.target.z-camera.position.z)*180/Math.PI-heading+720)%360)/45)%8]:'';this.html('.district-contract',contract?`<small>EXPLORAÇÃO OPCIONAL · ${contract.completed}/${contract.total}</small><b>${contract.contract.name}</b><span>Abra baús diferentes · ${contract.opened}/${contract.required}</span><small>${contractDirection} ${Math.round(contract.distance)} m até o baú · recompensa: item aleatório no chão</small>`:'<small>EXPLORAÇÃO</small><b>Rotas de abastecimento concluídas</b><span>Todos os contratos deste estágio recuperados.</span>');
  const reward=interact.waveRewardGuide;
  if(reward){const target=reward.drop.landing,direction=['↑','↗','→','↘','↓','↙','←','↖'][Math.round(((Math.atan2(target.x-camera.position.x,target.z-camera.position.z)*180/Math.PI-heading+720)%360)/45)%8];this.element.querySelector('.district-contract')!.insertAdjacentHTML('beforeend',`<span class="wave-reward-guide"><b>◈ RECOMPENSA DA HORDA</b><br>${reward.drop.item.name}<br><small>${reward.drop.waveField} · ${direction} ${Math.round(reward.distance)} m · [E] recolher</small></span>`);}
  this.html('.run-xp span',`NV. ${run.level} · ${run.xp} / ${run.nextLevelXP} XP`);(this.element.querySelector('.run-xp i') as HTMLElement).style.width=`${run.xp/run.nextLevelXP*100}%`;
  this.html('.run-hostiles',`<span>ONDA ${swarm.director.hordeMode?swarm.director.wave:Math.floor(swarm.director.time/36)+1}</span><b>${swarm.count} / ${swarm.populationCap}</b><small>${swarm.kills} abatidos · ${swarm.director.hordeMode?(swarm.director.intermission>0?(swarm.director.completedWaves>0?'RECOLHA O ITEM · PREPARE-SE':'PREPARE-SE'):Math.max(0,swarm.director.waveQuota-swarm.director.spawned)+' por nascer'):(swarm.director.time%36>27?'REAGRUPE-SE':'HORDA ATIVA')}</small>`);
  const boss=this.element.querySelector('.run-boss') as HTMLElement;boss.hidden=!swarm.boss||swarm.bossHP<=0;(boss.querySelector('i') as HTMLElement).style.width=`${swarm.bossHP/swarm.bossMaxHP*100}%`;boss.querySelector('small')!.textContent=`${Math.ceil(swarm.bossHP)} / ${swarm.bossMaxHP}`;
  const entry=interact.nearest,loot=interact.nearestLoot,box=this.element.querySelector('.run-interact') as HTMLElement;box.hidden=!entry&&!loot&&!(swarm.bossDeadTime>=5&&interact.atRift);
  box.innerHTML=swarm.bossDeadTime>=5&&interact.atRift?'<b>[E] ATRAVESSAR A FENDA</b><span>Créditos restantes viram XP.</span>':loot?`<b><i class="item-icon" style='${perkIcon(loot.item.icon)}'></i>${loot.item.name}</b><span>${loot.item.description}</span><span>[E] Recolher item</span>`:entry?`<b>${entry.name} · ◈ ${entry.cost}</b><span>[E] ${entry.kind==='altar'?'Oferecer créditos · 58% de chance':'Abrir · item aleatório'}</span>`:'';
  this.html('.run-toast',interact.messageTime>0?interact.message:'');
  const stats=run.stats;this.html('.run-stats',`<h2>EXTERMINADOR · NÍVEL ${run.level}</h2><p>Abata pragas para ganhar XP e créditos. Abra baús e combine melhorias. Derrote a Praga Alfa avance nas hordas. Chefes a cada cinco ondas.</p><dl>${[['Vida máxima',stats.maxHP.toFixed(0)],['Dano',`${Math.round(stats.damage*100)}%`],['Cadência',`${Math.round(stats.attackSpeed*100)}%`],['Armadura',stats.armor.toFixed(0)],['Crítico',`${Math.round(stats.crit*100)}%`],['Velocidade',`${Math.round(stats.moveSpeed*100)}%`],['Altura do salto',`${Math.round(stats.jump*100)}%`],['Pulos aéreos',String(stats.extraJumps)],['Recarga da esquiva',`${Math.round(stats.dodgeRecharge*100)}%`],['Regeneração',`${stats.regeneration.toFixed(1)} HP/s`],['Poder de habilidade',`${Math.round(stats.mp*100)}%`]].map(([label,value])=>`<dt>${label}</dt><dd>${value}</dd>`).join('')}</dl><small>Dourado: defesa e ouro · Gigante: atributos ×3 · Luminoso: dano e ataque extra</small><div class=inventory-detail>${[...run.inventory].map(([id,count])=>{const item=ITEMS.find(i=>i.id===id)!;return `<div title="${item.description}"><i class=item-icon style='${perkIcon(item.icon)}'></i><span>${item.name}<small>×${count} · ${item.description}</small></span></div>`;}).join('')}</div>`);
  const engine=camera.getEngine(),width=engine.getRenderWidth(),height=engine.getRenderHeight(),viewport=camera.viewport.toGlobal(width,height);
  const project=(p:Vector3)=>Vector3.Project(p,Matrix.Identity(),camera.getTransformationMatrix(),viewport),visible=(p:Vector3)=>p.z>=0&&p.z<=1&&p.x>=0&&p.x<=width&&p.y>=0&&p.y<=height;
  this.html('.damage-labels',swarm.labels.map(l=>{const p=project(new Vector3(l.position.x,l.position.y+(1-l.time)*.8,l.position.z));return visible(p)?`<b class="${l.crit?'crit':''}" style="left:${p.x/width*100}%;top:${p.y/height*100}%;opacity:${Math.min(1,l.time*3)}">${l.amount}${l.crit?'!':''}</b>`:'';}).join(''));
  this.html('.enemy-health-bars',swarm.actors.filter(a=>a.active&&!a.health.dead&&Math.hypot(a.root.position.x-camera.position.x,a.root.position.z-camera.position.z)<28).sort((a,b)=>Vector3.DistanceSquared(a.root.position,camera.position)-Vector3.DistanceSquared(b.root.position,camera.position)).slice(0,12).map(a=>{const p=project(new Vector3(a.root.position.x,a.body.getBoundingInfo().boundingBox.maximumWorld.y+.22,a.root.position.z)),name=`${ENEMIES[a.kind].name} ${ENEMY_AFFIXES[a.variant].label}`;return visible(p)?`<div class="enemy-health ${a.hit>0?'damaged':''}" style="left:${p.x/width*100}%;top:${p.y/height*100}%" aria-label="${name}: ${Math.ceil(a.health.current)} de ${a.health.maximum} de vida"><span>${name}</span><div><i class="health-trail" style="width:${a.healthTrail/a.health.maximum*100}%"></i><i style="width:${a.health.current/a.health.maximum*100}%"></i></div><small>${Math.ceil(a.health.current)} / ${a.health.maximum}</small></div>`:'';}).join(''));
  this.html('.world-supplies',interact.entries.filter(e=>!e.used).map(e=>{const d=Math.hypot(e.x-camera.position.x,e.z-camera.position.z),p=project(new Vector3(e.x,e.y+1.8,e.z));return d<35&&d>3&&visible(p)?`<b style="left:${p.x/width*100}%;top:${p.y/height*100}%;opacity:${Math.min(1,(35-d)/10)}">◈<small>${e.cost}</small></b>`:'';}).join(''));
 }
 dispose():void {this.controls.abort();this.element.remove();}
}
