from pathlib import Path
p=Path('src/world/FootingPresentation.ts');s=p.read_text(encoding='utf-8');s="import {DynamicTexture} from '@babylonjs/core/Materials/Textures/dynamicTexture';\n"+s;s=s.replace('private readonly mirror:MirrorTexture;', 'private crack:Mesh|undefined;private readonly mirror:MirrorTexture;')
pos=s.index(' private atWater(');s=s[:pos]+''' impactCracks(p:Vec3):void{
  this.crack?.dispose(false,true);const texture=new DynamicTexture('meteor-fractured-soil',{width:512,height:512},this.scene,false),ctx=texture.getContext();ctx.clearRect(0,0,512,512);ctx.strokeStyle='#19120c';ctx.lineCap='round';
  for(let i=0;i<11;i++){const a=i*2.399;let x=256,y=256;ctx.lineWidth=2.5+(i%3);ctx.beginPath();ctx.moveTo(x,y);for(let j=0;j<7;j++){const angle=a+Math.sin(i*7+j*3)*.28;x+=Math.cos(angle)*(19+j*2);y+=Math.sin(angle)*(19+j*2);ctx.lineTo(x,y);}ctx.stroke();ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(x*.75+64,y*.75+64);ctx.lineTo(x+Math.cos(a+.6)*25,y+Math.sin(a+.6)*25);ctx.stroke();}
  texture.hasAlpha=true;texture.update();const material=new StandardMaterial('meteor-cracked-earth',this.scene);material.diffuseTexture=texture;material.useAlphaFromDiffuseTexture=true;material.specularColor=Color3.Black();material.backFaceCulling=false;material.zOffset=-1;
  const mesh=CreateGround('meteor-impact-cracks',{width:3.6,height:3.6,subdivisions:12,updatable:true},this.scene),vertices=mesh.getVerticesData(VertexBuffer.PositionKind)!;for(let i=0;i<vertices.length;i+=3){const y=this.world.groundAt(p.x+vertices[i]!,p.z+vertices[i+2]!,p.y+1);vertices[i+1]=Number.isFinite(y)?y+.032:p.y+.032;}mesh.updateVerticesData(VertexBuffer.PositionKind,vertices);mesh.position.set(p.x,0,p.z);mesh.material=material;mesh.isPickable=false;this.crack=mesh;
 }
''' +s[pos:];s=s.replace('dispose():void {for(const p', 'dispose():void {this.crack?.dispose(false,true);for(const p');p.write_text(s,encoding='utf-8')
p=Path('scripts/prepare-species-audio.py');s=p.read_text(encoding='utf-8');s=s.replace("f'{key}-{i}.wav'", "('enemy-voice-'+file.lower().replace(' ','-')+'.wav')");p.write_text(s,encoding='utf-8')
p=Path('src/audio/RecordedAudio.ts');s=p.read_text(encoding='utf-8');s=s.replace("   const results=await Promise.allSettled", "   const decoded=new Map<string,Promise<AudioBuffer>>();const decode=(file:string)=>{let p=decoded.get(file);if(!p){p=fetch(file).then(r=>{if(!r.ok)throw Error(file);return r.arrayBuffer();}).then(b=>context.decodeAudioData(b));decoded.set(file,p);}return p;};\n   const results=await Promise.allSettled")
s=s.replace("files.map(async file=>{const r=await fetch(file);if(!r.ok)throw Error(file);return context.decodeAudioData(await r.arrayBuffer());})", "files.map(decode)");p.write_text(s,encoding='utf-8')
