from pathlib import Path
p=Path('src/game/EnemySwarm.ts');s=p.read_text(encoding='utf-8');s="import {ElementalEffects} from '../vfx/ElementalEffects';\nimport {BurningStatus} from '../combat/BurningStatus';\n"+s;s=s.replace('readonly actors:Actor[]=[];', 'readonly burning=new BurningStatus();private readonly elemental:ElementalEffects;private flameClock=0;readonly actors:Actor[]=[];');s=s.replace('this.effects=new CombatPresentation(scene);}', 'this.effects=new CombatPresentation(scene);this.elemental=new ElementalEffects(scene,world.collision);}')
s=s.replace('nextStage():void {this.debris.clear();', 'nextStage():void {this.elemental.clear();this.burning.clear();this.debris.clear();')
s=s.replace('this.initialize();this.navigation?.update(this.player.position);this.scheduler.update(dt);', "this.burning.update(dt,(owner,amount)=>{this.player.applyDamage({...this.damageContext(owner,amount,this.player.position,'incendiary_burn'),forceMagnitude:0,damageTags:['enemy','fire','dot']});});this.initialize();this.navigation?.update(this.player.position);this.scheduler.update(dt);")
s=s.replace("if(hit&&p.damage)this.player.applyDamage(this.damageContext(p.owner,p.damage,p.position,'seed_projectile'));", "if(hit&&p.damage){const before=this.player.hp;this.player.applyDamage(this.damageContext(p.owner,p.damage,p.position,p.impact?.zone==='fire'?'incendiary_projectile':'seed_projectile'));if(p.impact?.zone==='fire'&&this.player.hp<before)this.burning.ignite(p.owner);}")
s=s.replace("p.active=false;p.mesh.setEnabled(false);this.effects.burst(p.position,'seed',p.impact?1:.3);", "p.active=false;p.mesh.setEnabled(false);if(p.impact?.zone==='fire'){this.elemental.emit('explosion',p.position,.85);this.audio?.impact(true);}else this.effects.burst(p.position,'seed',p.impact?1:.3);")
s=s.replace("if(distance(position,this.player.position)<radius+.25&&Math.abs(position.y-this.player.position.y)<2.1)this.player.applyDamage(this.damageContext(owner,damage,position,kind));", "if(distance(position,this.player.position)<radius+.25&&Math.abs(position.y-this.player.position.y)<2.1){const before=this.player.hp;this.player.applyDamage(this.damageContext(owner,damage,position,kind));if(kind.startsWith('fire')&&this.player.hp<before)this.burning.ignite(owner,1.2);}")
s=s.replace('this.presentationTime+=dt;this.debris.update(dt);', '''this.presentationTime+=dt;this.elemental.update(dt);this.flameClock-=dt;if(this.flameClock<=0&&dt>0){this.flameClock=.11;for(const p of this.effects.projectiles)if(p.active&&p.delay<=0&&p.impact?.zone==='fire')this.elemental.emit('fire',p.position,.65);let fields=0;for(const w of this.effects.warnings)if(w.active&&w.kind.startsWith('fire')&&fields++<3){for(let i=0;i<2;i++){const a=this.presentationTime+i*3.14;this.elemental.emit('fire',new Vector3(w.position.x+Math.sin(a)*w.radius*.4,w.position.y+.06,w.position.z+Math.cos(a)*w.radius*.4),.8);}}}
    this.elemental.aura('fire',this.burning.remaining>0?[new Vector3(this.player.position.x,this.player.position.y+.6,this.player.position.z)]:[],this.presentationTime,this.burning.remaining>0?.65:0);
    this.debris.update(dt);''')
s=s.replace("mesh.renderOverlay=a.hit>0&&!a.health.dead;mesh.overlayColor=Color3.FromHexString('#fff0bc');mesh.overlayAlpha=Math.min(.48,a.hit*5);", "const charge=a.kind==='tomato'&&a.state==='windup'&&!a.health.dead?Math.min(1,a.time/ENEMY_BEHAVIORS.tomato.windup):0;mesh.renderOverlay=(a.hit>0||charge>0)&&!a.health.dead;mesh.overlayColor=charge>0?new Color3(1,.25,.025):Color3.FromHexString('#fff0bc');mesh.overlayAlpha=charge>0?.65*charge:Math.min(.48,a.hit*5);")
s=s.replace('dispose():void {this.ragdolls.clear();', 'dispose():void {this.elemental.dispose();this.burning.clear();this.ragdolls.clear();')
p.write_text(s,encoding='utf-8')
p=Path('src/vfx/CombatPresentation.ts');s=p.read_text(encoding='utf-8').replace('projectile.mesh.isVisible=Vector3.DistanceSquared(camera.position,projectile.position)>.4;',"projectile.mesh.isVisible=projectile.impact?.zone!=='fire'&&Vector3.DistanceSquared(camera.position,projectile.position)>.4;");p.write_text(s,encoding='utf-8')
p=Path('src/vfx/ElementalEffects.ts');s=p.read_text(encoding='utf-8').replace('const s=this.slots.find(s=>!s.active)??this.slots.reduce((a,b)=>a.serial<b.serial?a:b);','const available=this.slots.filter(s=>!this.auraSlots.includes(s));if(!available.length)return;const s=available.find(s=>!s.active)??available.reduce((a,b)=>a.serial<b.serial?a:b);');p.write_text(s,encoding='utf-8')
