from pathlib import Path
p=Path('src/game/PlayerScene.ts');s=p.read_text(encoding='utf-8');s=s.replace('this.skillAura=new SkillAura(this.scene);','this.skillAura=new SkillAura(this.scene,collision);void this.skillAura.load().then(()=>{if(!this.disposed)this.checkReady();});');s=s.replace('!this.weapons.ready ||','!this.weapons.ready || !this.skillAura.ready ||');s=s.replace('this.visual?.ready&&this.weapons?.ready&&','this.visual?.ready&&this.weapons?.ready&&this.skillAura?.ready&&');s=s.replace('this.visual.error||this.weapons.error||','this.visual.error||this.weapons.error||this.skillAura.error||');p.write_text(s,encoding='utf-8')
p=Path('src/combat/SkillTimeline.ts');s=p.read_text(encoding='utf-8');s=s.replace("release:1.22}","release:1.22,voiceEnd:3.40}",1).replace("release:1.22}","release:1.22,voiceEnd:3.36}",1).replace("release:1.2}","release:1.2,voiceEnd:3.90}",1);s=s.replace('duration=SKILL_CUES[tier].release+.22','duration=SKILL_CUES[tier].voiceEnd');s=s.replace('Math.max(SKILL_CUES[tier].release+.22,duration)','Math.min(SKILL_CUES[tier].voiceEnd,Math.max(SKILL_CUES[tier].release+.22,duration))');p.write_text(s,encoding='utf-8')
p=Path('src/audio/RecordedAudio.ts');s=p.read_text(encoding='utf-8');s="import {SKILL_CUES} from '../combat/SkillTimeline';\n"+s;s=s.replace('const start=ctx.currentTime+.04;this.duckUntil=start+clip.duration;', 'const start=ctx.currentTime+.04,duration=Math.min(clip.duration,SKILL_CUES[tier].voiceEnd);gain.gain.setValueAtTime(this.enabled?1:0,start);gain.gain.setValueAtTime(this.enabled?1:0,start+duration-.06);gain.gain.linearRampToValueAtTime(0,start+duration);this.duckUntil=start+duration;');s=s.replace('source.start(start);return{clock:()=>Math.max(0,ctx.currentTime-start),duration:clip.duration};','source.start(start);source.stop(start+duration);return{clock:()=>Math.max(0,ctx.currentTime-start),duration};');p.write_text(s,encoding='utf-8')
p=Path('src/combat/DualPistols.ts');s=p.read_text(encoding='utf-8');s=s.replace('    if(this.fanIndex<this.fanTotal){this.fanClock-=dt;', '    if(this.actionClock&&this.actionClock()>=this.actionDuration){this.fanIndex=this.fanTotal;this.barrageIndex=this.barrageTotal;this.stormRemaining=0;}\n    if(this.fanIndex<this.fanTotal){this.fanClock-=dt;');s=s.replace('duration/(this.fanTotal-1)','duration/this.fanTotal').replace('duration/(this.barrageTotal-1)','duration/this.barrageTotal');p.write_text(s,encoding='utf-8')
p=Path('src/run/MonsterDirector.ts');s=p.read_text(encoding='utf-8').replace('  bossKilled():void', '  retireLivingEnemy():void {if(this.hordeMode)this.spawned=Math.max(0,this.spawned-1);}\n  bossKilled():void');p.write_text(s,encoding='utf-8')
p=Path('src/game/EnemySwarm.ts');s=p.read_text(encoding='utf-8').replace('if(actor){actor.active=false;', 'if(actor){this.director.retireLivingEnemy();actor.active=false;').replace('if(!retired)return false;retired.active=false;', 'if(!retired)return false;this.director.retireLivingEnemy();retired.active=false;');p.write_text(s,encoding='utf-8')
p=Path('tests/hordes-arsenal-catalog.test.ts');s=p.read_text(encoding='utf-8');start=s.index("it('keeps the performance active through the original voice duration");s=s[:start]+'''it.each([1,2,3] as const)('skill %i ends at vocal cutoff even when the file has a longer tail',tier=>{const t=new SkillTimeline(),release=vi.fn();t.start(tier,6.034);const end=SKILL_CUES[tier].voiceEnd;expect(t.duration).toBe(end);t.update(1.5,release);expect(t.closeVisible).toBe(false);t.update(end-.001,release);expect(t.active).toBe(true);t.update(end,release);expect(t.active).toBe(false);expect(t.actionProgress).toBe(1);expect(release).toHaveBeenCalledTimes(1);});
it('replaces enemies retired for performance instead of counting them as defeated',()=>{const d=new MonsterDirector(new RunRNG('retire').stream('director'),1,50,true);d.intermission=0;d.spawned=d.waveQuota;d.retireLivingEnemy();for(let i=0;i<100;i++)d.update(.1,0,0,()=>false,12);expect(d.completedWaves).toBe(0);expect(d.spawned).toBe(d.waveQuota-1);let spawned=0;d.update(1,0,0,()=>{spawned++;return true;},12);expect(spawned).toBe(1);d.update(.1,0,1,()=>false,12);expect(d.completedWaves).toBe(0);d.update(.1,1,0,()=>false,12);expect(d.completedWaves).toBe(1);});
''';p.write_text(s,encoding='utf-8')
p=Path('tests/mp.test.ts');s=p.read_text(encoding='utf-8');s+='''\nit.each([1,2,3] as const)('skill %i discards queued emissions after a frame stall beyond the voice end',tier=>{const r=setup(false,true);let clock=0;try{r.weapons.releaseSkill(tier,true,2.2,()=>clock);r.weapons.fixedUpdate(1/60,false);const before=r.weapons.skillShots;clock=3.5;for(let i=0;i<90;i++)r.weapons.fixedUpdate(1/60,false);expect(r.weapons.skillShots).toBe(before);expect(r.weapons.stormRemaining).toBe(0);}finally{r.dispose();}});\n''';p.write_text(s,encoding='utf-8')
