from pathlib import Path
p=Path('src/audio/RecordedAudio.ts');s=p.read_text().replace(' playerHurt():', " casing(strength=1,_x=0):void {this.play('casing',.32*strength,1,0,.045);}\n reload():void{this.play('reload',.7,1,0,.1);}\n playerHurt():");p.write_text(s)
p=Path('src/combat/DualPistols.ts');s=p.read_text();s="import {PistolMagazine} from './PistolMagazine';\nimport {ShellCasings} from '../vfx/ShellCasings';\n"+s;s=s.replace('  readonly cadence=', '  readonly magazine=new PistolMagazine();private readonly casings:ShellCasings;\n  readonly cadence=');s=s.replace('    this.effects=new ShotEffects(scene);','    this.effects=new ShotEffects(scene);this.casings=new ShellCasings(scene,yard.collision,audio);');s=s.replace('  updatePose(dt:', '''  requestReload():boolean{if(this.barrageIndex<14||this.stormRemaining>0||this.fanIndex<10)return false;if(!this.magazine.request())return false;this.audio.reload?.();return true;}
  updatePose(dt:''');s=s.replace('this.hitTime=Math.max(0,this.hitTime-dt);this.effects.update(dt);','this.hitTime=Math.max(0,this.hitTime-dt);this.effects.update(dt);this.casings.update(dt);');s=s.replace('    this.cadence.update(dt,fire&&', '    this.magazine.update(dt);this.visual.reloadProgress=this.magazine.reloading?this.magazine.progress:-1;\n    if(this.magazine.ammo===0&&!this.magazine.reloading)this.requestReload();\n    this.cadence.update(dt,fire&&!this.magazine.reloading&&this.magazine.ammo>0&&');s=s.replace('    this.lastSide=side;', '    if(!this.magazine.consume())return;\n    this.lastSide=side;');s=s.replace('this.effects.muzzle(origin);', 'this.effects.muzzle(origin);this.casings.eject(origin,this.camera.forward,side);');s=s.replace('this.effects.dispose();for(const root', 'this.effects.dispose();this.casings.dispose();for(const root');s=s.replace('this.fan.clear();this.fanIndex', 'this.magazine.cancel();this.visual.reloadProgress=-1;this.fan.clear();this.fanIndex');
s=s.replace('root.computeWorldMatrix(true);continue;', '''const p=this.magazine.progress;
        if(this.magazine.reloading&&p>.18&&p<.84){const flight=(p-.18)/.66;root.position.y=Math.sin(Math.PI*flight)*1.35;root.position.x=(side===0?1:-1)*Math.sin(Math.PI*flight)*.13;root.rotationQuaternion=Quaternion.RotationAxis(Vector3.Right(),flight*Math.PI*4);}
        root.computeWorldMatrix(true);continue;''');p.write_text(s)
p=Path('src/animation/CharacterVisual.ts');s=p.read_text().replace('  private fanCastTime=0;', '  reloadProgress=-1;\n  private fanCastTime=0;');s=s.replace('    if(this.preparation){', "    if(this.reloadProgress>=0){this.machine.sample('ReloadCast',this.reloadProgress,dt);this.root.computeWorldMatrix(true);for(const grip of this.grips)grip?.computeWorldMatrix(true);return;}\n    if(this.preparation){");p.write_text(s)
p=Path('src/input/GameInput.ts');s=p.read_text().replace('interact?:number|undefined', 'reload?:boolean; interact?:number|undefined');s=s.replace('  private jump = false;', '  private reload=false;\n  private jump = false;');s=s.replace("if(!e.repeat&&e.code==='KeyE')", "if(!e.repeat&&e.code==='KeyR')this.reload=true;\n      if(!e.repeat&&e.code==='KeyE')");s=s.replace('jump: this.jump, dodge:', 'reload:this.reload,jump: this.jump, dodge:');s=s.replace('this.jump = false; this.dodge = false;', 'this.reload=false;this.jump = false; this.dodge = false;');p.write_text(s)
p=Path('src/game/PlayerScene.ts');s=p.read_text().replace('    this.player.fixedUpdate(dt,input,this.input.yaw);', '    if(input.reload){this.player.sprinting=false;this.weapons.requestReload();}\n    this.player.fixedUpdate(dt,this.weapons.magazine.reloading?EMPTY_INPUT:input,this.input.yaw);');s=s.replace('this.mp.update(dt,input.charging)', 'this.mp.update(dt,input.charging&&!this.weapons.magazine.reloading)');s=s.replace('this.skillPending||this.cinematic.active||this.player.hp<=0','this.skillPending||this.cinematic.active||this.weapons.magazine.reloading||this.player.hp<=0');s=s.replace('    if(this.cinematic.preparing)this.camera.skillClose', '    if(this.weapons.magazine.reloading)this.camera.skillClose(this.visual.position,this.input.yaw,2,Math.min(1,this.weapons.magazine.progress*4, (1-this.weapons.magazine.progress)*5));\n    if(this.cinematic.preparing)this.camera.skillClose');s=s.replace("    if(name==='heal')", "    if(name==='reload'){this.weapons.magazine.ammo=Math.min(20,this.weapons.magazine.ammo);this.weapons.requestReload();}\n    if(name==='heal')");p.write_text(s)
p=Path('src/ui/PlayerHUD.ts');s=p.read_text().replace('<b>∞</b><small>SEM RECARGA</small>','<b>50 / 50</b><small>R · RECARREGAR</small>');s=s.replace('<span><kbd>CLIQUE</kbd> Disparar</span>','<span><kbd>CLIQUE</kbd> Disparar</span><span><kbd>R</kbd> Recarregar</span>');s=s.replace("    this.hp.textContent=", "    const ammo=this.element.querySelector('.weapon-readout b');if(ammo){ammo.textContent=pistols.magazine.ammo+' / '+pistols.magazine.capacity;this.element.querySelector('.weapon-readout small')!.textContent=pistols.magazine.reloading?'RECARREGANDO · '+Math.round(pistols.magazine.progress*100)+'%':'R · RECARREGAR';}\n    this.hp.textContent=");s=s.replace('Pistolas sem recarga','Carregador de 50 balas');p.write_text(s)
p=Path('scripts/author-directional-animation.mjs');s=p.read_text().replace("['PrepareStorm',1.2,0,0]", "['PrepareStorm',1.2,0,0],['ReloadCast',2.15,0,0]");s=s.replace("fan=name==='FanCast'||name.startsWith('Prepare')", "fan=name==='FanCast'||name==='ReloadCast'||name.startsWith('Prepare')");s=s.replace("if(fan){bend('Spine'", "if(name==='PrepareMortal')worldShift(hips,new Vector3(0,-.12*pulse,-.07*pulse));\n  if(fan){bend('Spine'");s=s.replace("new Vector3(sign*(name==='PrepareStorm'?-.32*pulse:.12+.48*Math.sin(Math.PI*posePhase)),.02,.9)", "new Vector3(sign*(name==='PrepareStorm'?-.32*pulse:.12+.48*Math.sin(Math.PI*posePhase)),name==='ReloadCast'?Math.sin(phase*Math.PI*3)*.9:name==='PrepareMortal'?.45*pulse:.02,.9)");p.write_text(s)
