from pathlib import Path
p=Path('src/game/PlayerScene.ts');s=p.read_text(encoding='utf-8');s="import {ElementalEffects,ELEMENTS,type ElementKind} from '../vfx/ElementalEffects';\n"+s;s=s.replace('private poseReview=false;',"private poseReview=false;private readonly elements:ElementalEffects;private elementPreview:ElementKind|undefined;private elementClock=0;private auraClock=0;private auraLast=-1;")
s=s.replace('this.skillAura=new SkillAura(this.scene,collision);','this.elements=new ElementalEffects(this.scene,collision);this.skillAura=new SkillAura(this.scene,collision);')
s=s.replace('this.weapons.updatePose(worldDt);this.skillAura.update(this.cinematic,this.visual.position,this.weapons);', '''this.weapons.updatePose(worldDt);this.skillAura.update(this.cinematic,this.visual.position,this.weapons);
    this.elements.update(animDt);
    if(this.elementPreview&&animDt>0){this.elementClock-=animDt;if(this.elementClock<=0){this.elementClock=1.6;const p=this.visual.position.add(this.camera.forward.scale(2.4));p.y=this.player.position.y+.03;this.elements.emit(this.elementPreview,p);}}
    if(this.cinematic.active){if(this.cinematic.elapsed<this.auraLast){this.elements.clear();this.auraClock=0;}const elapsed=this.cinematic.elapsed;if(elapsed>=this.auraClock){this.auraClock=elapsed+.22;for(const side of [0,1] as const)this.elements.emit('electricity',this.weapons.muzzlePose(side).position,.55);if(this.cinematic.preparing&&elapsed<.7)this.elements.emit('earth',this.visual.position,.38);}this.auraLast=elapsed;}else if(this.auraLast>=0){this.elements.clear();this.auraLast=-1;this.auraClock=0;}
''')
s=s.replace("private cancelCinematic():void{this.poseReview=false;", "private cancelCinematic():void{this.elements?.clear();this.auraClock=0;this.auraLast=-1;this.poseReview=false;")
s=s.replace("    if(name.startsWith('pose-skill'))", "    if(name==='element-off'){this.elementPreview=undefined;this.elements.clear();}\n    if(name.startsWith('element-')&&ELEMENTS.includes(name.slice(8) as ElementKind)){this.elementPreview=name.slice(8) as ElementKind;this.elementClock=0;}\n    if(name.startsWith('pose-skill'))")
s=s.replace('this.cutIn.dispose();this.skillAura.dispose();','this.cutIn.dispose();this.skillAura.dispose();this.elements.dispose();');p.write_text(s,encoding='utf-8')
p=Path('src/debug/DebugOverlay.ts');s=p.read_text(encoding='utf-8');s=s.replace("[['pose-skill1'", "[['element-fire','VFX Fogo'],['element-water','VFX Água'],['element-earth','VFX Terra'],['element-electricity','VFX Eletricidade'],['element-darkness','VFX Trevas'],['element-explosion','VFX Explosão'],['element-off','Encerrar prévia VFX'],['pose-skill1'");p.write_text(s,encoding='utf-8')
p=Path('src/camera/ThirdPersonCamera.ts');s=p.read_text(encoding='utf-8').replace('position.y+.94,position.z),delta=forward.scale(2.65-progress*.25)','position.y+.76,position.z),delta=forward.scale(3.35-progress*.22)');s=s.replace('delta.y=-.10','delta.y=.12');p.write_text(s,encoding='utf-8')
p=Path('docs/OBJECTIVES_QUEUE.md');s=p.read_text(encoding='utf-8')+'\n- [ ] Biblioteca reutilizável de fogo, água, terra, eletricidade, trevas e explosão, com materiais/texturas, limites de custo e prévia no diagnóstico.\n';p.write_text(s,encoding='utf-8')
