from pathlib import Path
p=Path('src/combat/DualPistols.ts');s=p.read_text();s="import {CreateBox} from '@babylonjs/core/Meshes/Builders/boxBuilder';\nimport {PBRMaterial} from '@babylonjs/core/Materials/PBR/pbrMaterial';\nimport type {Mesh} from '@babylonjs/core/Meshes/mesh';\n"+s;s=s.replace('  private readonly weapons:', '  private readonly reloadMagazines:Mesh[]=[];private readonly tossStarts:({position:Vector3;rotation:Quaternion}|undefined)[]=[];\n  private readonly weapons:');s=s.replace('    for(let side=0;side<2;side++) {\n      const root=', "    const magazineMaterial=new PBRMaterial('pistol-magazine-steel',scene);magazineMaterial.albedoColor=new Color3(.11,.13,.13);magazineMaterial.metallic=.85;magazineMaterial.roughness=.36;\n    for(let side=0;side<2;side++) {\n      const magazine=CreateBox('replacement-magazine-'+side,{width:.045,height:.13,depth:.06},scene);magazine.material=magazineMaterial;magazine.isPickable=false;magazine.setEnabled(false);this.reloadMagazines.push(magazine);\n      const root=");a=s.index('      if(grip){');b=s.index('      root.position.copyFrom(hand?',a);s=s[:a]+'''      if(grip){
        const p=this.magazine.progress,air=this.magazine.reloading&&p>.18&&p<.84;grip.computeWorldMatrix(true);const gripPosition=grip.getAbsolutePosition(),gripRotation=Quaternion.Identity();grip.getWorldMatrix().decompose(undefined,gripRotation);
        if(air){let start=this.tossStarts[side];if(!start){start={position:gripPosition.clone(),rotation:gripRotation.clone()};this.tossStarts[side]=start;}const flight=(p-.18)/.66;
          root.parent=null;Vector3.LerpToRef(start.position,gripPosition,flight*flight,root.position);root.position.y+=Math.sin(Math.PI*flight)*1.12;root.rotationQuaternion=Quaternion.RotationAxis(new Vector3(Math.cos(this.camera.camera.rotation.y),0,-Math.sin(this.camera.camera.rotation.y)),flight*Math.PI*4).multiply(Quaternion.Slerp(start.rotation,gripRotation,flight));
        }else{this.tossStarts[side]=undefined;root.parent=grip;root.position.setAll(0);root.rotationQuaternion=Quaternion.Identity();}
        root.computeWorldMatrix(true);const magazine=this.reloadMagazines[side]!;magazine.setEnabled(air&&p>.38&&p<.66);
        if(magazine.isEnabled()){const phase=(p-.38)/.28;Vector3.LerpToRef(this.visual.position.add(new Vector3(side===0?.25:-.25,.88,.08)),root.getAbsolutePosition(),phase,magazine.position);magazine.rotationQuaternion=root.rotationQuaternion?.clone()??Quaternion.Identity();}
        continue;
      }
'''+s[b:];s=s.replace('this.casings.dispose();for(const root', 'this.casings.dispose();for(const magazine of this.reloadMagazines)magazine.dispose();for(const root');p.write_text(s)
# Damage/armor effects are applied to player in the fixed step; update pickups immediately for HUD too.
p=Path('src/game/PlayerScene.ts');s=p.read_text().replace("this.events.on('ItemPicked',()=>{this.audio.charge(2);", "this.events.on('ItemPicked',()=>{this.player.maxHP=this.progression.stats.maxHP;this.audio.charge(2);");p.write_text(s)
# Make the fire shell originate at the receiver rather than the muzzle tip.
p=Path('src/vfx/ShellCasings.ts');s=p.read_text().replace('c.mesh.position.copyFrom(position);','c.mesh.position.copyFrom(position).subtractInPlace(forward.scale(.19));');p.write_text(s)
