import {copyFileSync,mkdirSync,writeFileSync} from 'node:fs';
const bank={};mkdirSync('public/audio/foley',{recursive:true});
function add(group,source,name){const path=`foley/${name}`;copyFileSync(source,`public/audio/${path}`);(bank[group]??=[]).push(`/audio/${path}`);}
for(const surface of ['grass','wood','concrete'])for(let i=0;i<5;i++)add(surface,`art/source/foley-impact/Audio/footstep_${surface}_00${i}.ogg`,`${surface}-${i}.ogg`);
for(let i=1;i<=6;i++)add('water',`art/source/foley-water/ezwa-water_splash/water_splash-0${i}.flac`,`water-${i}.flac`);
for(let i=1;i<=6;i++)add('swish',`art/source/foley-swish/swosh-0${i}.flac`,`swish-${i}.flac`);
for(let i=0;i<4;i++){add('impact',`art/source/foley-impact/Audio/impactSoft_medium_00${i}.ogg`,`impact-${i}.ogg`);add('heavy',`art/source/foley-impact/Audio/impactSoft_heavy_00${i}.ogg`,`heavy-${i}.ogg`);add('charge',`art/source/foley-impact/Audio/impactBell_heavy_00${i}.ogg`,`charge-${i}.ogg`);}
for(const [group,files] of Object.entries({growl:['Beast Growl 1','Beast Growl 2','Beast Growl 3','Beast Growl 4'],attack:['Yucky Beast 1','Yucky Beast 2','Yucky Beast 3'],death:['Dieing Beast','Dieing pixie'],spawn:['Demon Call One Voice','Beast Growl'],hurt:['Yucky Beast 4','Yucky Beast 5','Yucky Beast 6']}))for(const [i,file] of files.entries())add(group,`art/source/foley-monsters/Monsters or Beasts/${file}.wav`,`${group}-${i}.wav`);
bank.pistol=[1,2,3,4].map(i=>`/audio/pistol-${i}.wav`);writeFileSync('public/audio/foley-manifest.json',JSON.stringify(bank,null,2));
writeFileSync('docs/foley-sources.json',JSON.stringify([{author:'Kenney',license:'CC0',url:'https://kenney.nl/assets/impact-sounds',use:'Grass, wood, concrete footsteps, impacts and bells'},{author:'pauliuw',license:'CC0',url:'https://opengameart.org/content/monster-or-beast-sounds',use:'Monster voice recordings'},{author:'qubodup',license:'CC0',url:'https://opengameart.org/content/swish-bamboo-stick-weapon-swhoshes',use:'Recorded bamboo air swishes for dodge and skill motion'},{author:'ezwa / qubodup',license:'CC0',url:'https://opengameart.org/content/6-short-water-splashes',use:'Water footsteps and splashes'},{author:'Tabasco',license:'CC0',url:'https://opengameart.org/content/gunshot-sounds',use:'Recorded CZ pistol shots'}],null,2));console.log(Object.fromEntries(Object.entries(bank).map(([k,v])=>[k,v.length])));
