from pathlib import Path
p=Path('src/audio/RecordedAudio.ts');s=p.read_text().replace('pan=0,gap=.05):void', 'pan=0,gap=.05,delay=0):void').replace('source.start();source.onended=', 'source.start(context.currentTime+delay);source.onended=').replace("this.play('reload',.7,1,0,.1)", "this.play('reload',.7,1,0,.1,.5)");p.write_text(s)
p=Path('src/game/PlayerScene.ts');s=p.read_text().replace("catch(error){console.warn('Cinemática sem áudio disponível'", "catch(error){if(this.disposed||version!==this.castVersion)return;console.warn('Cinemática sem áudio disponível'");p.write_text(s)
p=Path('docs/CURRENT_IMPLEMENTATION.md');s=p.read_text();s=s.replace('MP I alterna dois disparos perfurantes; seu rastro viaja, mas o dano continua hitscan. MP II distribui 14 disparos ao longo do mortal para evitar o pico simultâneo. MP III alterna mira por braço e pose cruzada com IK.', 'MP I lança uma sequência de balas curvas em leque com ricochete físico por segmentos, sem alvo travado. MP II distribui a barragem durante o mortal e sua finalização; MP III alterna mira por braço e pose cruzada com IK. As três atuações acompanham a duração integral das vozes fornecidas.');s=s.replace('90 PNGs importados com integridade binária; o catálogo jogável atual tem 12 efeitos empilháveis. Ícones disponíveis não significam 90 efeitos implementados.', '90 PNGs associados a 90 definições jogáveis e sorteáveis. Os 78 itens antes ausentes agora concedem atributos cumulativos; os 12 anteriores mantêm o balanceamento e os hooks de incêndio, explosão e cura por abate. São 90 itens, não 90 tipos diferentes de mecânica. Inventário compacto e catálogo completo no Tab.');s=s.replace('87 testes em 19 arquivos aprovados; TypeScript e build de produção aprovados. Registros: art/latest-tests.log e art/latest-build.log.', '203 testes em 22 arquivos aprovados; TypeScript e build de produção aprovados. Registros: art/validation-expanded.log e art/build-current.log.');s=s.replace('expansão dos itens/mapas', 'balanceamento do catálogo e expansão dos mapas');s+='''
## Combate, arsenal e cinematográficas — revisão acumulada desta sessão

- Dano recebido: vinheta, indicador direcional, número de HP perdido, barra com atraso, câmera e gravação de impacto destacada. Regeneração espera dois segundos após dano. Conferido no navegador com −25 HP.
- Tiros comuns não interrompem a FSM do inimigo. Impactos fortes podem atordoar por 0,18 s, com intervalo de 0,85 s. Corpos vivos bloqueiam por varredura e deslizamento; o jogador não empurra agentes como um carrinho. Trombadas geram resposta breve.
- Rolar em movimento inicia corrida a 12,6 m/s; parar ou atirar interrompe; salto mantém a corrida. O motor usa velocidade realmente percorrida para as passadas.
- Varredura contínua da cápsula e câmera contra triângulos de cenário, incluindo paredes profundas das ilhas, quinas aéreas e tetos. Recuperação de sobreposição em volumes fechados retorna ao último piso seguro sem curar. Testes usam a geometria real da ilha a −4/−8/−12/−16 m.
- Seis clipes de locomoção novos: recuo e deslocamento lateral à esquerda/direita, andando e correndo. Seleção pela direção local, mistura diagonal, transição de estados; 61 amostras por clipe. Mesh, skin, materiais, texturas e sockets preservados.
- 50 balas compartilhadas pelas duas pistolas; R ou esvaziar inicia recarga de 2,15 s. Armas são lançadas em arco, giram, recebem carregadores e voltam às mãos. O som gravado entra 0,5 s após iniciar; habilidades usam sua própria munição de MP.
- Cartuchos reutilizam 48 elementos, sem corpos Havok extras. Som de contato real, dois ressaltos e descarte após cinco segundos. Gravações CC0 e licenças em foley-sources.json.
- Close 3D com preparo heroico durante o grito; câmera retorna ao combate no começo do nome. Base baixa, pernas afastadas, braços abertos; aura turquesa nas pistolas, poeira e fragmentos texturizados. O HUD desaparece durante o close.
- Áudio original preservado: duração real aproximada de 6,034 s / 5,799 s / 5,878 s. Relógio do AudioContext conduz preparo e ação; pausa suspende a voz, uma nova skill não corta a fala anterior. Cues iniciais 1,22 / 1,22 / 1,20 s, estimados por transcrição local; o terceiro tem menor confiança e pode precisar de ajuste fino após escuta humana. Auditoria em skill-voice-audit.json. Não foi feito upload externo desses áudios.
- A sequência normal de MP I tem 48 balas ao longo da atuação; MP II até 48 disparos distribuídos. Os testes diretos sem voz mantêm durações curtas para avaliar balística isoladamente. O mortal físico ocupa a abertura de MP II, seguido da postura de disparo até finalizar a voz.

## Modo de hordas atual

A entrada padrão usa hordas sucessivas no mapa existente. Cada onda contém 7 + 3 × número da onda de inimigos comuns; as ondas 5/10/15… também têm chefe. Spawns respeitam o orçamento de população. Concluir exige todos mortos, concede automaticamente um item aleatório do catálogo e inicia intervalo de oito segundos. Não há escolha. Baús continuam com a coleta física própria, independente da recompensa da onda.

Vida dos inimigos multiplica por 1,16 a cada onda e dano cresce 12 pontos percentuais por onda. A simulação de dez ondas verificou chefes em 5/10, um prêmio por onda, falhas de spawn sem avanço indevido e limite de população. No navegador: onda 1 concluída, Célula de descarga recebida, onda 2 iniciada; adicionar o catálogo inteiro mostrou a pilha da célula em ×2 e vida máxima em 403 no nível 2.

A expedição com fenda permanece em ?mode=expedition; não foi criado outro mapa. O modo de treino permanece em ?mode=training.

## Arte e revisão

Fonte editável atual do jogador: art/blender/Gunslinger_Directional_And_Skills.blend. Gerador de clipes: scripts/author-directional-animation.mjs, lendo a cópia com grips corrigidos em art/processed/gunslinger-before-directional.glb. O script save-directional-blend.py salva o .blend sem reexportar/destruir o GLB original.

F1 inclui revisão de pose I/II/III e saída da revisão, recarga, conclusão de onda, onda 5 e catálogo de 90 itens. São controles QA, sem efeito numa nova partida. Revisão final do conjunto visual ainda não equivale à referência. Durante esta sessão houve amostras de 36–48 FPS com dez inimigos e 28 FPS logo após dez mortes/ragdolls; posteriormente o navegador de fundo foi limitado a aproximadamente 1 FPS. Essas condições não certificam desempenho sustentado.
''';p.write_text(s)
p=Path('docs/OBJECTIVES_QUEUE.md');s=p.read_text();at=s.index('## Sensação de combate e parkour');s=s[:at]+s[at:].replace('- [ ]','- [x]');s=s.replace('Habilidade 1: dois disparos perceptíveis e projéteis perfurantes distintos.', 'Habilidade 1: pedido histórico de dois disparos, substituído depois pelo leque ricocheteante.');s+='\nRevisão de 07/09: 203 testes / 22 arquivos, TypeScript e build aprovados. Os itens marcados nesta sessão indicam implementação e verificações descritas em CURRENT_IMPLEMENTATION.md; equivalência visual global e 60 FPS permanecem abertos.\n';p.write_text(s)
p=Path('docs/MILESTONES.md');s=p.read_text().replace('dois disparos MP I','leque ricocheteante MP I').replace('90 ícones importados (12 efeitos jogáveis)','90 itens configurados e cumulativos').replace('87 testes em 19 arquivos','203 testes em 22 arquivos').replace('mais efeitos de itens e mapa seguinte distinto','balanceamento dos itens e mapa seguinte distinto');s+='\n- [x] Resposta de dano, colisão cápsula/malha, corrida pós-esquiva e recuo/strafe.\n- [x] 50 balas, recarga acrobática, cartuchos com gravações reais.\n- [x] Hordas progressivas com recompensa aleatória por onda e chefe a cada cinco.\n- [x] Preparo heroico, aura/terra e atuações sincronizadas à duração original das três vozes.\n';p.write_text(s)
p=Path('docs/CONTINUE_ON_D.md');s=p.read_text().replace('87 testes / 19 arquivos','203 testes / 22 arquivos').replace('Os 90 ícones não equivalem ainda a 90 efeitos distintos.', 'Os 90 ícones agora têm 90 definições sorteáveis: atributos cumulativos e hooks existentes, não 90 mecânicas únicas.');s=s.replace('expansão de itens/mapas','balanceamento do catálogo e expansão dos mapas');s+='\nA entrada padrão agora é modo de hordas com recompensa por conclusão e chefe a cada cinco ondas. Pistolas com 50 balas, recarga no R, cartuchos gravados. Cinemáticas usam as três vozes originais, preparo heroico e duração completa do áudio. Clipes direcionais e nova fonte: art/blender/Gunslinger_Directional_And_Skills.blend. Consulte CURRENT_IMPLEMENTATION.md para detalhes e limites.\n';p.write_text(s)
p=Path('README.md');s=p.read_text().replace('A cena padrão tem uma rodada completa com cinco espécies originais, chefe, progressão, itens, economia e passagem de estágio.', 'A cena padrão tem hordas progressivas, cinco espécies originais, chefe a cada cinco ondas e recompensa aleatória do catálogo de 90 itens ao concluir cada onda.');s=s.replace('botão esquerdo dispara.', 'botão esquerdo dispara. R recarrega o carregador compartilhado de 50 balas; Tab abre atributos e inventário.');s=s.replace('MP perfurante, barragem com mortal e tempestade de três segundos', 'leque ricocheteante, barragem com mortal e tempestade com duração sincronizada à voz');s=s.replace('art/blender/Gunslinger_Final.blend','art/blender/Gunslinger_Directional_And_Skills.blend').replace('combinam perfuração, mortal com barragem e tempestade de tiros.', 'combinam leque ricocheteante, mortal com barragem e tempestade de tiros, precedidos por close heroico durante o grito. A atuação segue a duração original dos áudios. A expedição anterior está em `?mode=expedition`.');p.write_text(s)
