from pathlib import Path
p=Path('src/camera/ThirdPersonCamera.ts');s=p.read_text().replace('  impulse(strength:', '''  skillClose(position:Vec3,yaw:number,tier:1|2|3,progress:number):void {
    const forward=new Vector3(Math.sin(yaw),0,Math.cos(yaw)),right=new Vector3(Math.cos(yaw),0,-Math.sin(yaw));
    const pivot=new Vector3(position.x,position.y+1.28,position.z),delta=forward.scale(2.25-progress*.22).add(right.scale(tier===2?-.8:.8));delta.y=.17;
    const hit=this.world.sweepSphere(pivot,delta,.16,true);const close=pivot.add(delta.scale(hit?Math.max(.05,hit.time-.04):1));
    const weight=Math.min(1,progress*9);this.camera.position.copyFrom(Vector3.Lerp(this.camera.position,close,weight));
    this.camera.setTarget(Vector3.Lerp(this.camera.position.add(this.forward.scale(3)),pivot,weight));this.camera.rotation.z=(tier===3?-.035:.025)*weight;
  }
  impulse(strength:''');p.write_text(s)
p=Path('src/game/PlayerScene.ts');s=p.read_text();s="import {SkillTimeline,type SkillTier} from '../combat/SkillTimeline';\nimport {SkillCutIn} from '../ui/SkillCutIn';\n"+s;s=s.replace('  private paused=false;', '  private readonly cinematic=new SkillTimeline();private readonly cutIn=new SkillCutIn();private voiceClock:(()=>number)|undefined;private skillPending=false;private castVersion=0;private castYaw=0;private castPitch=0;\n  private paused=false;');s=s.replace('    const input=this.paused?', '    if(this.skillPending||this.cinematic.preparing)return;\n    const input=this.paused?');s=s.replace('if(released){this.player.sprinting=false;this.weapons.releaseSkill(released);if(released===2)this.player.barrageRetreat();}','if(released){void this.requestSkill(released);return;}');s=s.replace('    const animDt=this.paused||!this.started?0:dt;', '''    const animDt=this.paused||!this.started?0:dt;
    if(this.cinematic.active){this.input.yaw=this.castYaw;this.input.pitch=this.castPitch;if(animDt>0&&this.voiceClock)this.cinematic.update(this.voiceClock(),tier=>{this.visual.endPreparation();this.camera.update(this.player.position,this.castYaw,this.castPitch,dt);this.weapons.releaseSkill(tier,true);if(tier===2)this.player.barrageRetreat();});if(this.cinematic.preparing)this.visual.prepareSkill(this.cinematic.tier,this.cinematic.progress);}
    this.cutIn.update(this.cinematic,this.started&&!this.paused);
    const worldDt=this.cinematic.preparing||this.skillPending?0:animDt;''');s=s.replace('    this.weapons.updatePose(animDt);','    if(this.cinematic.preparing)this.camera.skillClose(this.visual.position,this.castYaw,this.cinematic.tier,this.cinematic.progress);\n    this.weapons.updatePose(worldDt);');s=s.replace('this.enemies.update(animDt);this.footing.update(animDt);this.abyss?.update(animDt);','this.enemies.update(worldDt);this.footing.update(worldDt);this.abyss?.update(worldDt);');s=s.replace('this.yard.update(animDt);','this.yard.update(worldDt);');s=s.replace('this.scene.physicsEnabled=this.started&&!this.paused;', 'this.scene.physicsEnabled=this.started&&!this.paused&&!this.cinematic.preparing&&!this.skillPending;');s=s.replace('  setPaused(paused:', '''  private async requestSkill(tier:SkillTier):Promise<void>{
    if(this.skillPending||this.cinematic.active||this.player.hp<=0)return;
    this.skillPending=true;const version=++this.castVersion;this.player.sprinting=false;this.castYaw=this.input.yaw;this.castPitch=this.input.pitch;
    try{const clock=await this.audio.voice(tier);if(this.disposed||version!==this.castVersion)return;this.voiceClock=clock;this.cinematic.start(tier);this.visual.prepareSkill(tier,0);}
    catch(error){console.warn('Cinemática sem áudio disponível',error);this.weapons.releaseSkill(tier);if(tier===2)this.player.barrageRetreat();}
    finally{this.skillPending=false;}
  }
  private cancelCinematic():void{this.castVersion++;this.skillPending=false;this.cinematic.cancel();this.visual.endPreparation();this.audio.cancelVoice();}
  setPaused(paused:''');s=s.replace("this.events.on('PlayerKilled',()=>{this.started=false;", "this.events.on('PlayerKilled',()=>{this.cancelCinematic();this.started=false;");s=s.replace('this.mp.cancel();this.weapons.cancelSkills();','this.mp.cancel();this.cancelCinematic();this.weapons.cancelSkills();');s=s.replace('this.weapons.releaseSkill(tier);if(tier===2)this.player.barrageRetreat();}}', 'void this.requestSkill(tier);}}');s=s.replace('this.disposed=true;if(this.yard', 'this.disposed=true;this.cancelCinematic();this.cutIn.dispose();if(this.yard');p.write_text(s)
